version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./next/Dockerfile
    ports:
      - '8000:3000'
    volumes:
      - type: bind
        source: ./next
        target: /app
      - type: bind
        source: ./next/node_modules
        target: /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    tty: true
    stdin_open: true
volumes:
  node_modules: