version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./next/Dockerfile
    ports:
      - '8000:3000'
    volumes:
      - ./next:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    tty: true
    stdin_open: true
volumes:
  node_modules: